using Microsoft.AspNetCore.Http;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPG_game.Model
{
    public class GameStory
    {
        public Dictionary<int, Location> Locations = new Dictionary<int, Location>();
        public Dictionary<RandomEnum, List<int>> RandomLocations = new Dictionary<RandomEnum, List<int>>();
        readonly Random _random;

        public int GetRandom(RandomEnum random)
        {
            List<int> list = RandomLocations[random];
            int start = _random.Next(0, list.Count);
            return list[start];
        }

        public GameStory(Random random)
        {
            _random = random;
            RandomLocations.Add(RandomEnum.Hairstyle, new List<int> { 103, 105, 106});
            RandomLocations.Add(RandomEnum.Date, new List<int> { 700, 701 });
            RandomLocations.Add(RandomEnum.DateSuccess, new List<int> { 704, 705, 706 });
            RandomLocations.Add(RandomEnum.KostikOptions, new List<int> { 408, 409, 410 });
            RandomLocations.Add(RandomEnum.DinaOptions, new List<int> { 411, 412, 413 });
            RandomLocations.Add(RandomEnum.MuseumAloneOptions, new List<int> { 414, 415 });
            RandomLocations.Add(RandomEnum.CinemaPepaOptions, new List<int> { 308, 309 });
            RandomLocations.Add(RandomEnum.CinemaJanaOptions, new List<int> { 315, 316 });
            RandomLocations.Add(RandomEnum.MovieOptions, new List<int> { 311, 312, 313, 314 });
            RandomLocations.Add(RandomEnum.ParkBenchOptions, new List<int> { 209, 210, 215, 216 });
            RandomLocations.Add(RandomEnum.ClubOptions, new List<int> { 620, 621, 622, 623, 624 });
            RandomLocations.Add(RandomEnum.ClubExperience, new List<int> { 614, 615, 616 });
            RandomLocations.Add(RandomEnum.ClubEnter, new List<int> { 602, 603 });
            RandomLocations.Add(RandomEnum.MajkOptions, new List<int> { 618, 619 });

            //Startup, konfigurace postavy (1-9)
            //Locations.Add(1, new Location() { Name = "Konfigurace tvé postavy", Description = "Tvým prvním úkolem bude vybrat si základní vlastnosti tvého hrdiny / ky. 😈", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = 2 } } });
            Locations.Add(1, new Location() { Name = "Vítej", Description = "Děkujeme, že sis vybral zrovna naší hru. Tvým úkolem bude plnit mise, které ti postupně bude udělovat aplikace na tvém telefonu. Je tu pro tebe, aby ti pomohla naučit se seznamovat a tím splnit cíl téhle hry (5 úspěšných schůzek). Nesnaž se volat o pomoc, mobil má vlastní hlavu a ozve se jenom, když bude on sám chtít :). Přejeme pěknou zábavu.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jdeme na to!", NextLocationId = 3 } } });
            Locations.Add(3, new Location() { Name = "Pokoj", Description = "Jsi ve svém pokoji, tvůj telefon píše: \"Je čas objevovat. Vyjdi ven!\"", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Vydat se ven", NextLocationId = 10 } } });
            Locations.Add(4, new Location() { Name = "Pokoj", Description = "Jsi ve svém pokoji.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Vydat se ven", NextLocationId = 10 } } });
            Locations.Add(5, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Úkol splněn. Tvůj level se zvýšil.\"", LevelUp = true, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = 10 } } }); ;
            Locations.Add(6, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Tento úkol se ti bohužel nepovedl, zkus se na toto místo vrátit později.\"", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = 10 } } });

            //Náměstí (10-19)
            Locations.Add(10, new Location() { Name = "Náměstí", Description = "Přišel jsi na náměstí, můžeš pokračovat několika různými směry. Který si vybereš?", PathToUnlock = new LocationPath() { LocationId = 207, PathId = 0 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zpět do pokoje", NextLocationId = 4 }, new Path() { PathId = 1, PathDescription = "Do kavárny", NextLocationId = 20 }, new Path() { PathId = 2, PathDescription = "Do kadeřnictví", NextLocationId = 100 }, new Path() { PathId = 3, PathDescription = "Do parku", NextLocationId = 200 }, new Path() { PathId = 4, PathDescription = "Do kina", NextLocationId = 300 }, new Path() { PathId = 5, PathDescription = "Do muzea", NextLocationId = 400 }, new Path() { PathId = 6, PathDescription = "Do obchodu", NextLocationId = 500 }, new Path() { PathId = 7, PathDescription = "Do klubu", IsLocked = false, NextLocationId = 600 } } });
            //Locations.Add(11, new Location() { Name = "Náměstí", Description = "Jsi ve svém pokoji, máš telefon.. a ten píše: Jdi ven!", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Vydat se ven", NextLocationId = 10 } } });

            //Kavárna (20-29)
            Locations.Add(20, new Location() { Name = "Kavárna Moonbucks", Description = "Ocitl ses v kavárně, utíkej si vybrat něco ze zdejší obsáhlé nabídky nápojů. Za pultem se na tebe usmívá mladý barista 🧑‍💼 (nebo baristka 🧑‍💼?)", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zpět na náměstí", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Jít k pultu", NextLocationId = 21 } } });
            // + mobilní aplikace - "získej něčí číslo"
            Locations.Add(21, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Nový úkol - Osměl se a řekni si někomu o číslo.\" ", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Jít k baristovi", NextLocationId = 22 }, { new Path { PathId = 1, PathDescription = "Jít k baristce", NextLocationId = 27 } } } });
            Locations.Add(22, new Location() { Name = "Kavárna Moonbucks", Description = "Barista: \"Dobrý den, co si dáte?\"", Cost = 100, Coffee = true, RedirectPaths = new List<RedirectPath> { new RedirectPath() { LocationId = 40, PathId = 0, NewNextLocationId = 41 } }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Objednat si nápoj", NextLocationId = 23 } } });
            Locations.Add(23, new Location() { Name = "Kavárna Moonbucks", Description = "Našel jsi místo na sezení. Čekáš a pozoruješ baristu za pultem. Barista po chvilce volá tvé jméno a ty si jdeš vyzvednout nápoj.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Poděkovat a odejít", NextLocationId = 6 }, new Path() { PathId = 1, PathDescription = "Požádat baristu o číslo", NextLocationId = 24 }, new Path() { PathId = 2, PathDescription = "Zeptat se na jméno", NextLocationId = 26 } } });
            Locations.Add(24, new Location() { Name = "Kavárna Moonbucks", Description = "Barista: \"Promiňte, nedávám své číslo jen tak na potkání.\"", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Poděkovat a odejít", NextLocationId = 5 }, new Path() { PathId = 2, PathDescription = "Zeptat se na jméno", NextLocationId = 25 } } });
            Locations.Add(25, new Location() { Name = "Kavárna Moonbucks", Description = "Barista si s úsměvem ukáže na jmenovku. \"Jsem Maniel. K vaším službám.\"", Person = new Person() { Name = "Maniel", LocationId = 750, ClubLocationId = 625 }, RedirectPaths = new List<RedirectPath> { new RedirectPath() { LocationId = 10, PathId = 1, NewNextLocationId = 40 }, new RedirectPath { LocationId = 40, PathId = 0, NewNextLocationId = 41 } }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Rozloučit se a odejít", NextLocationId = 5 } } });
            Locations.Add(26, new Location() { Name = "Kavárna Moonbucks", Description = "Barista si s úsměvem ukáže na jmenovku. \"Jsem Maniel. K vaším službám.\"", Person = new Person() { Name = "Maniel", LocationId = 750, ClubLocationId = 625 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Rozloučit se a odejít", NextLocationId = 6 } } });

            Locations.Add(27, new Location() { Name = "Kavárna Moonbucks", Description = "Baristka: \"Dobrý den, co si dáte?\"", Cost = 100, Coffee = true, RedirectPaths = new List<RedirectPath> { new RedirectPath() { LocationId = 40, PathId = 1, NewNextLocationId = 42 } }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Objednat si nápoj", NextLocationId = 28 } } });
            Locations.Add(28, new Location() { Name = "Kavárna Moonbucks", Description = "Našel jsi místo na sezení. Čekáš a pozoruješ baristku za pultem. Baristka po chvilce volá tvé jméno a ty si jdeš vyzvednout nápoj.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Poděkovat a odejít", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Požádat baristku o číslo", NextLocationId = 29 }, new Path() { PathId = 2, PathDescription = "Zeptat se na jméno", NextLocationId = 31 } } });
            Locations.Add(29, new Location() { Name = "Kavárna Moonbucks", Description = "Baristka: \"Promiňte, nedávám své číslo jen tak na potkání.\"", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Poděkovat a odejít", NextLocationId = 5 }, new Path() { PathId = 2, PathDescription = "Zeptat se na jméno", NextLocationId = 30 } } });
            Locations.Add(30, new Location() { Name = "Kavárna Moonbucks", Description = "Baristka se na tebe zadívá a po chvilce klidně odpoví.\"Maniela. Užijte si kávu. Nashledanou.\"", Person = new Person() { Name = "Maniela", LocationId = 751, ClubLocationId = 626 }, RedirectPaths = new List<RedirectPath> { new RedirectPath() { LocationId = 10, PathId = 1, NewNextLocationId = 40 }, new RedirectPath() { LocationId = 40, PathId = 1, NewNextLocationId = 42 } }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Rozloučit se a odejít", NextLocationId = 5 } } });
            Locations.Add(31, new Location() { Name = "Kavárna Moonbucks", Description = "Baristka se na tebe zadívá a po chvilce klidně odpoví.\"Maniela. Užijte si kávu. Nashledanou.\"", Person = new Person() { Name = "Maniela", LocationId = 751, ClubLocationId = 626 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Rozloučit se a odejít", NextLocationId = 10 } } });
            //Nová kavárna (bez úkolu)
            Locations.Add(40, new Location() { Name = "Kavárna Moonbucks", Description = "Tak jsi tu znovu. Co si dáš?", RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 23, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 24, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 25, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 26, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 28, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 29, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 30, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 31, PathId = 0, NewNextLocationId = 10 } }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít k baristovi", NextLocationId = 22 }, new Path() { PathId = 1, PathDescription = "Jít k baristce", NextLocationId = 27 }, new Path() { PathId = 2, PathDescription = "Zpět na náměstí", NextLocationId = 10 } } });
            Locations.Add(41, new Location() { Name = "Kavárna Moonbucks", Description = "Maniel: \"Dobrý den, co si dneska dáte?\"", Cost = 100, Coffee = true, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Objednat si", NextLocationId = 43 } } });
            Locations.Add(42, new Location() { Name = "Kavárna Moonbucks", Description = "Maniela: \"Dobrý den, co si dneska dáte?\"", Cost = 100, Coffee = true, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Objednat si", NextLocationId = 43 } } });
            Locations.Add(43, new Location() { Name = "Kavárna Moonbucks", Description = "Po chvilce je zavoláno tvé jméno a ty si jdeš vyzvednout svůj nápoj k pultu.", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Poděkovat a odejít", NextLocationId = 10 } } });



            //Kadeřnictví (100-199)
            Locations.Add(100, new Location() { Name = "Kadeřnictví u Zohana", Description = "Nacházíš se v kadeřnictví, na zdi proti tobě je několik fotografií zajímavých účesů, které se teď nosí.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zpět na náměstí", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Posadit se do křesla", NextLocationId = 101 } } });
            // + mobilní aplikace - "nech si udělat nový účes"
            Locations.Add(101, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Nový úkol - Nechej si udělat nějaký moderní účes, díky kterému budeš přitažlivější pro své okolí.\" ", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Nechat se ostříhat od kadeřníka", NextLocationId = 102 }, new Path { PathId = 1, PathDescription = "Nechat se ostříhat od kadeřnice", NextLocationId = 104 } } });
            Locations.Add(102, new Location() { Name = "Kadeřnictví u Zohana", Description = "Sedl sis a kadeřník povídá: \"Dobrý den, jmenuji se Zohan, co uděláme s Vašimi vlasy?\" ", Cost = 350, Hairstyle = true, Person = new Person() { Name = "Zohan", LocationId = 752, ClubLocationId = 630 }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Popsat jaký účes si představuješ", NextLocationIds = RandomLocations[RandomEnum.Hairstyle] }, new Path { PathId = 1, PathDescription = "Nechat volbu účesu na kadeřníkovi", NextLocationId = GetRandom(RandomEnum.Hairstyle) } } });
            Locations.Add(103, new Location() { Name = "WOW... účes se opravdu povedl", Description = "Tvůj nový účes je vážně skvělý, sluší ti to. 😉", RedirectPaths = new List<RedirectPath> { new RedirectPath() { LocationId = 10, PathId = 2, NewNextLocationId = 120 } }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Poděkovat, zaplatit a odejít", NextLocationId = 5 } } });
            Locations.Add(104, new Location() { Name = "Kadeřnictví u Zohana", Description = "Sedl sis a kadeřnice povídá: \"Dobrý den, jmenuji se Břetislava, jaký účes si představujete?\" ", Cost = 300, Hairstyle = true, Person = new Person() { Name = "Břetislava Matějková", LocationId = 753, ClubLocationId = 631 }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Popsat jaký účes si představuješ", NextLocationIds = RandomLocations[RandomEnum.Hairstyle] }, new Path { PathId = 1, PathDescription = "Nechat volbu účesu na kadeřnici", NextLocationId = GetRandom(RandomEnum.Hairstyle) } } });
            Locations.Add(105, new Location() { Name = "Kadeřnictví u Zohana", Description = "Sice to není úplně to, co sis představoval, ale vyloženě ošklivý ten účet také není.", RedirectPaths = new List<RedirectPath> { new RedirectPath() { LocationId = 10, PathId = 2, NewNextLocationId = 120 } }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Zaplatit a popřát hodně štěstí", NextLocationId = 5 } } });
            Locations.Add(106, new Location() { Name = "HRŮZA", Description = "Vypadáš jako oškubané kuře, tvé vlasy jsou ale natolik krátké, že jediná možnost je jen kšiltovka nebo klobouk. 😢", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Rozhořčeně se rozloučit a odejít", NextLocationId = 6 } } });
            //Nové kadeřnictví (bez úkolu)
            Locations.Add(120, new Location() { Name = "Kadeřnictví u Zohana", Description = "Znovu jsi přišel do kadeřnictví. Co si necháš ostříhat tentokrát?", RedirectPaths = new List<RedirectPath>() { new RedirectPath { LocationId = 103, PathId = 0, NewNextLocationId = 10}, new RedirectPath { LocationId = 105, PathId = 0, NewNextLocationId = 10}, new RedirectPath { LocationId = 106, PathId = 0, NewNextLocationId = 10} }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít k Zohanovi", NextLocationId = 102 }, new Path { PathId = 1, PathDescription = "Jít k Břetislavě", NextLocationId = 104}, new Path { PathId = 2, PathDescription = "Vrátit se na náměstí", NextLocationId = 10} } });;


            //Locations.Add()

            //Park (200-299)
            Locations.Add(200, new Location() { Name = "Park Cestovatelů", Description = "Jsi v parku, kde tě mezi rodinami s dětmi hned na první pohled zaujal blázen Havel Škrlík.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zpět na náměstí", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Jít k rybníku", NextLocationId = 699, IsLocked = true }, new Path() { PathId = 2, PathDescription = "Volně se procházet parkem", NextLocationId = 201 } } });
            // + mobilní aplikace - "zlepši náladu"
            Locations.Add(201, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Nový úkol - Zlepši někomu náladu, aby všichni viděli, jak máš dobré srdce.\"", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Jít za holčičkou, které se odkutálel míč", NextLocationId = 202 }, new Path { PathId = 1, PathDescription = "Přijít blíže k Havlovi", NextLocationId = 203 }, new Path { PathId = 2, PathDescription = "Udělat zábavné vystoupení pro děti", NextLocationId = 206 } } });
            Locations.Add(202, new Location() { Name = "Park Cestovatelů", Description = "Pomáháš malé holčičce chytit míč, už ho skoro máš, ale omylem na něj šlápneš a on praskne. Holčička pláče, její rodiče tě zabíjí pohledem a ty se snažíš zneviditelnit.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Vzít nohy na ramena a utéct z Parku", NextLocationId = 6 } } });
            Locations.Add(203, new Location() { Name = "Park Cestovatelů", Description = "Jakmile se příblížíš k Havlovi, vidíš že není tak šílený, jak to zpovzdálí vypadlo. Jen stále něco hledá a točí se okolo lavičky jako šílenec.", Person = new Person() { Name = "Havel Škrlík", LocationId = 754 }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Zeptat se, co hledá", NextLocationId = 204 } } });
            Locations.Add(204, new Location() { Name = "Park Cestovatelů", Description = "Havel odpovídá na tvoji otázku: \"Tož ty omladino, já jsem tu ztratil moje okuláry.\" Ty mu je samozřejmě pomáháš hledat a po chvíli je v trávě skutečně objevíš. \"Já je tu marně hledal 20 let a ty je najdeš hned. Jak se ti mohu odvděčit?\" povídá Havel", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Svěřit se tomuto chápavému důchodci se svými problémy", NextLocationId = 205 } } });
            Locations.Add(205, new Location() { Name = "Park Cestovatelů", Description = "Důchodce Škrlík vyslechl všechny tvé problémy a povídá: \"To já byl zamlada neodolatelný díky jednomu místu, kde se randilo jak po másle. Prozradím ti, kde to je. 🤪\" a řekně ti, kde přesně tento rybník najdeš.", RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 200, PathId = 2, NewNextLocationId = 207} }, PathsToUnlock = new List<LocationPath>() { new LocationPath() { LocationId = 200, PathId = 1 }, new LocationPath() { LocationId = 500, PathId = 1 } }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Poděkovat mu za cennou informaci a odejít", NextLocationId = 5 } } });
            Locations.Add(206, new Location() { Name = "Park Cestovatelů", Description = "Jelikož tvé herecké schopnosti nejsou zrovna na Hollywood, tak u dětí spíše místo smíchu převládají slzy. 🙂", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Zahanbeně odejít", NextLocationId = 6 } } });
            
            //Park 2

            Locations.Add(207, new Location() { Name = "Park Cestovatelů", Description = "Procházíš se po parku...", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Jít si popovídat s Havlem", NextLocationId = 208, HoverDescription = "Havel už si s tebou nechce povídat." }, new Path() { PathId = 1, PathDescription = "Sednout si na lavičku", NextLocationIds = RandomLocations[RandomEnum.ParkBenchOptions] }, new Path() { PathId = 2, PathDescription = "Udělat si piknik", NextLocationId = 211, IsLocked = true, HoverDescription = "Nemůžeš dělat piknik, protože na něj nemáš nakoupeno." }, new Path() { PathId = 3, PathDescription = "Odejít", NextLocationId = 10} } });
            Locations.Add(208, new Location() { Name = "Park Cestovatelů", Description = "Havel měl velikou radost, že tě zase viděl. Ptal se tě, jestli už jsi někoho vzal na jeho randící místo.", PathToLock = new LocationPath() { LocationId = 207, PathId = 0 }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Odejít z parku", NextLocationId = 10 }, new Path() { PathId = 0, PathDescription = "Zůstat v parku", NextLocationId = 207 } } });

            Locations.Add(209, new Location() { Name = "Park Cestovatelů", Description = "Sedíš a díváš se, jak si děti házejí s létajícím talířem.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Zvednout se z lavičky", NextLocationId = 207 } } });
            Locations.Add(210, new Location() { Name = "Park Cestovatelů", Description = "Sedíš a pozoruješ holuby, kteří vypadají, že za chvíli ze všeho toho nadrobeného rohlíku prasknou.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Zvednout se z lavičky", NextLocationId = 207 } } });
            Locations.Add(215, new Location() { Name = "Park Cestovatelů", Description = "Sedíš a pozoruješ mladý pár, který projíždí s kočárkem.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Zvednout se z lavičky", NextLocationId = 207 } } });
            Locations.Add(216, new Location() { Name = "Park Cestovatelů", Description = "Sedíš a pozoruješ starší paní a pána, jak se spolu smějí na protejší lavičce.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Zvednout se z lavičky", NextLocationId = 207 } } });

            Locations.Add(211, new Location() { Name = "Park Cestovatelů", Description = "Je tu tak krásně. Perfektní místo na schůzku. Co toho využít?", Picnic = true, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Udělat si piknik sám", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Pozvat někoho na piknik", NextLocationId = 213} } });
            Locations.Add(212, new Location() { Name = "Park Cestovatelů", Description = "Každý někdy potřebuje čas pro sebe.  A ty sis ho perfektně užil.", PathToLock = new LocationPath() { LocationId = 207, PathId = 2 }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Zůstat v parku", NextLocationId = 207 }, new Path() { PathId = 1, PathDescription = "Odejít z parku", NextLocationId = 10 } } });
            Locations.Add(213, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Na horní liště vlevo máš pod seznamem Známí uložené všechny, které jsi zatím stihl ve hře potkat. Kliknutím na jméno je můžeš pozvat na piknikové rande. Bude ale pouze na nich, jestli tvé pozvání přijmou.\"", RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 701, PathId = 1, NewNextLocationId = 213}, new RedirectPath() { LocationId = 701, PathId = 0, NewNextLocationId = 214 } }, DateAllowed = true, PathToLock = new LocationPath() { LocationId = 207, PathId = 2}, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Nelíbí se mi nikdo ze seznamu, udělám si piknik sám", NextLocationId = 212} } } );
            Locations.Add(214, new Location() { Name = "Park cestovatelů", Description = "Protože nikdo nepřijal tvou nabídku, rozhodl ses, že si piknik uděláš sám a užiješ si všechno to dobré jídlo, než se zkazí.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zůstat v parku", NextLocationId = 207 }, new Path() { PathId = 1, PathDescription = "Odejít z parku", NextLocationId = 10 } } });

            //KINO (300-399)
            Locations.Add(300, new Location() { Name = "Kino Cinnamon", Description = "Nacházíš se v kině, je tu poměrně dost lidí, ale vidíš kousek ode dveří vidíš kluka a holku.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zpět na náměstí", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Jít za nimi", NextLocationId = 301 } } });
            // + mobilní aplikace - "najdi někoho nového"
            Locations.Add(301, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Nový úkol - Najdi někoho sympatického a seznam se s ním.\"", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Jít k dívce", NextLocationId = 302 }, new Path { PathId = 1, PathDescription = "Jít k chlapci", NextLocationId = 304 }, new Path { PathId = 2, PathDescription = "Jít si koupit lístek", NextLocationId = 305 } } });
            Locations.Add(302, new Location() { Name = "Kino Cinnamon", Description = "Přicházíš k dívce, která se na tebe zadívá a říká: \"Ahoj, jmenuji se Jana Perioda, nechceš si koupit popcorn a zajít na StarWars? 😍\"", Person = new Person() { Name = "Jana Perioda", LocationId = 756, ClubLocationId = 627}, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Ano", NextLocationId = 303 }, new Path { PathId = 1, PathDescription = "Ne", NextLocationId = 6 } } });
            Locations.Add(303, new Location() { Name = "Kino Cinnamon", Description = "S Janou Periodou si rozumíte, po kině jste si ještě společně zašli na drink.", Cost = 250, Cinema = true, PathToLock = new LocationPath() { LocationId = 300, PathId = 1 }, RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 10, PathId = 4, NewNextLocationId = 306 } }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Doprovodit Janu domů, popřát dobrou noc a odejít", NextLocationId = 5 } } });
            Locations.Add(304, new Location() { Name = "Kino Cinnamon", Description = "Oslovuješ chlapce a ptáš se: \"Jak se jmenuješ?\", on odpovídá \"Do toho ti nic není!\" a kousne tě do ruky. 😬", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Radši odejít pryč", NextLocationId = 6 } } });
            Locations.Add(305, new Location() { Name = "Kino Cinnamon", Description = "Kupuješ si lístek na film V síti, kde po menším pádu ze schodů potkáváš velmi sympatickou Lenku, se kterou se během večera spřátelíš.", Cost = 150, Cinema = true, Person = new Person() { Name = "Lenka", LocationId = 757, ClubLocationId = 628 }, RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 10, PathId = 4, NewNextLocationId = 306} }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Doprovodit Lenku domů, popřát dobrou noc a odejít", NextLocationId = 5 } } });

            //druhé Kino
            Locations.Add(306, new Location() { Name = "Kino Cinnamon", Description = "Znovu jsi navštívil kino.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zpět na náměstí", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Jít na film", NextLocationId = 307 } } });
            Locations.Add(307, new Location() { Name = "Kino Cinnamon", Description = "Cestou k pokladně znovu zahlédneš tu samou dívku a chlapce.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít k chlapci a pozvat ho na film", NextLocationIds = RandomLocations[RandomEnum.CinemaPepaOptions] }, new Path() { PathId = 1, PathDescription = "Jít k dívce a pozvat ji na film", NextLocationIds = RandomLocations[RandomEnum.CinemaJanaOptions] }, new Path() { PathId = 2, PathDescription = "Pokračovat k pokladně", NextLocationId = 310 } } } );
            Locations.Add(308, new Location() { Name = "Možná někdy jindy", Description = "Pepa Hřebec bohužel tvé pozvání odmítl.", Person = new Person() { Name = "Pepa Hřebec", LocationId = 755, ClubLocationId = 629 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Koupit si popcorn a jít na film sám", NextLocationId = 310 }, new Path() { PathId = 1, PathDescription = "Odejít z kina", NextLocationId = 10 } } });
            Locations.Add(309, new Location() { Name = "Super!", Description = "Pepa Hřebec tvé pozvání přijal. Rychle mu mazej koupit něco na zub.", Person = new Person() { Name = "Pepa Hřebec", LocationId = 755, ClubLocationId = 629 }, PathToUnlock = new LocationPath { LocationId = 310, PathId = 1}, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Koupit popcorn a jít vybrat film", NextLocationId = 310 } } });
            Locations.Add(310, new Location() { Name = "Kino Cinnamon", Description = "Teď už jen vybrat film a vydat se do sálu.", Cost = 160, Cinema = true, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Vybrat sám", NextLocationIds = RandomLocations[RandomEnum.MovieOptions] }, new Path() { PathId = 1, PathDescription = "Nechat vybrat svou společnost", NextLocationIds = RandomLocations[RandomEnum.MovieOptions], IsLocked = true }, new Path() { PathId = 0, PathDescription = "Nechat si poradit u pokladny", NextLocationIds = RandomLocations[RandomEnum.MovieOptions] } } });
            Locations.Add(311, new Location() { Name = "To byla pecka!", Description = "Tak tohle byl jeden z nejlepších filmů, které jsi za poslední dobu viděl.", PathToLock = new LocationPath() { LocationId = 310, PathId = 1 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 } } });
            Locations.Add(312, new Location() { Name = "Neurazí, nenadchne", Description = "Čekal jsi, že to bude větší pecka, ale svých peněz nelituješ.", PathToLock = new LocationPath() { LocationId = 310, PathId = 1 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 } } });
            Locations.Add(313, new Location() { Name = "Nespi!", Description = "Kdyby se tě někdo zeptal, o čem tenhle film byl, asi bys byl leda tak schopný popsat prvních deset minut. Chtělo to trochu víc akce.", PathToLock = new LocationPath() { LocationId = 310, PathId = 1 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 } } });
            Locations.Add(314, new Location() { Name = "Co to bylo?", Description = "Vycházíš ze sálu a za boha nemůžeš pochopit, jak si někdo myslel, že zveřejnit tenhle film bude dobrý nápad.", PathToLock = new LocationPath() { LocationId = 310, PathId = 1 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 } } });
            Locations.Add(315, new Location() { Name = "Možná někdy jindy", Description = "Jana Perioda bohužel tvé pozvání odmítla.", Person = new Person() { Name = "Jana Perioda", LocationId = 756, ClubLocationId = 627 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Koupit si popcorn a jít na film sám", NextLocationId = 310 }, new Path() { PathId = 1, PathDescription = "Odejít z kina", NextLocationId = 10 } } });
            Locations.Add(316, new Location() { Name = "Super!", Description = "Jana Perioda tvé pozvání přijala. Rychle ji mazej koupit něco na zub.", Person = new Person() { Name = "Jana Perioda", LocationId = 756, ClubLocationId = 627}, PathToUnlock = new LocationPath { LocationId = 310, PathId = 1 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Koupit popcorn a jít vybrat film", NextLocationId = 310 } } });



            //Muzeum (400-499)
            Locations.Add(400, new Location() { Name = "Muzeum", Description = "Vešel jsi do muzea. Doufejme, že se ti tu bude líbit. Protože tu stovku za vstup už ti nikdo nevrátí. U brány ti oznámili, že můžeš počkat na průvodkyni.", Cost = 100, Museum = true, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = 401 } } });
            // + mobilní aplikace - "rozšiř své vědomostní obzory."
            Locations.Add(401, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Nový úkol - Nasbírej nové vědomosti. Všichni milují inteligenty.\"", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Počkat na průvodkyni", NextLocationId = 402 }, /*new Path() { PathId = 1, PathDescription = "Prohlédnout si muzeum na vlastní pěst", NextLocationId = 406, IsLocked = true }, */ new Path() { PathId = 1, PathDescription = "Odejít z muzea", NextLocationId = 6 } } });
            Locations.Add(402, new Location() { Name = "Muzeum", Description = "Po pár minutách za sebou uslyšíš blížící se kroky. Otočíš se za zvukem. \"To jste tu jenom vy? Máte štěstí, dneska mě máte jenom pro sebe.\" Dívka se afektovaně usměje. \"Dobrý den. Jmenuji se Dina Veselá a dnes budu vaší průvodkyní. Kdykoliv budete mít nějaké dotazy týkající se vystavených aparátů nebo čehokoliv jiného, neváhejte se zeptat. Nyní mě prosím následujte.\"", Person = new Person() { Name = "Dina Veselá", LocationId = 758, ClubLocationId = 632 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Následovat Dinu", NextLocationId = 403 } } });
            Locations.Add(403, new Location() { Name = "Muzeum", Description = "Čas se vleče a ty pomalu začínáš svých utracených peněz litovat. Dina se sice ze začátku zdála jako fajn partie, teď máš ale co dělat, abys nezíval po každém jejím slově. Vtom tvou pozornost upoutá vytáhlý kluk, který se krčí u jedné z vystavených koster. \" Jeho si nevšímejte. Tenhle kluk sem chodí častěji, než uklízečky. Ne, že ty by tu byly nějak často,\" řekne Dina, mračíc se přitom na chuchvalec prachu poblíž její nohy. \"Říkáme mu Kostík, protože nikdo vlastně neví, jak se doopravdy jmenuje.\" ", Person = new Person() { Name = "Kostík", LocationId = 759, ClubLocationId = 633 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zeptat se na Kostíka", NextLocationId = 404 }, new Path { PathId = 1, PathDescription = "Zeptat se na exponáty", NextLocationId = 405 } } });
            Locations.Add(404, new Location() { Name = "Muzeum", Description = "Dina si odfkne. \"Nic moc o něm nevím. Jenom to, že nám brigádníkům rád krade návštěvníky. Vždycky skončí u něj. Nevím, co tak zajímavého jim vypráví, ale všichni vždy odcházejí nadmíru spokojeni. Vedení se ho párkrát dokonce pokusilo zaměstnat, ale marně. Tak dostal alespoň doživotní vstupné zdarma.\"", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Pokračovat v prohlídce s Dinou", NextLocationId = 405 }, new Path { PathId = 1, PathDescription = "Jít za Kostíkem", NextLocationId = 406 } } });
            Locations.Add(405, new Location() { Name = "Muzeum", Description = "Prohlídka trvá ještě dalších 20 minut. \"Na konec vám chci poděkovat za pozornost a doufám, že vás zas brzy uvidíme v našem muzeu. \" Dina se otočí na patě a odkráčí zpátky, odkud přišla. Nebylo to zas tak špatné. Když ses přenesl přes Dinin předetailovaný přednes, zjistil jsi, že si opravdu něco málo nového pamatuješ. Sice ještě stále nevíš, k čemu ti při seznamování bude dobré vědět, jak velký byl brontosaurus, ale kdo ví.", RedirectPaths = new List<RedirectPath>() { new RedirectPath { LocationId = 10, PathId = 5, NewNextLocationId = 407} }, Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Odejít z muzea", NextLocationId = 5 } } });
            Locations.Add(406, new Location() { Name = "Muzeum", Description = "Jemně se omluvíš Dině a pomalu zamíříš směrem, kde jsi ještě před chvilkou zahlédl postávat zrzavého návštěvníka. Teď už tu ale nestojí. Otáčíš se všemi směry, ale ne a ne ho najít...  ", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Odejít z muzea", NextLocationId = 6 } } });

            //druhé Muzeum
            Locations.Add(407, new Location() { Name = "Muzeum", Description = "Znovu jsi přišel do muzea. Už když jsi vešel, všiml sis, že Kostík tu je znovu.", Cost = 100, Museum = true, Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Jít za Kostíkem", NextLocationIds = RandomLocations[RandomEnum.KostikOptions] }, new Path { PathId = 1, PathDescription = "Zkusit najít Dinu", NextLocationIds = RandomLocations[RandomEnum.DinaOptions] }, new Path { PathId = 2, PathDescription = "Prohlédnout si muzeum sám", NextLocationIds = RandomLocations[RandomEnum.MuseumAloneOptions]}, new Path { PathId = 3, PathDescription = "Jít pryč z muzea", NextLocationId = 10} } });
            Locations.Add(408, new Location() { Name = "Muzeum", Description = "Přišel jsi ke Kostíkovi. Ten ti povídal o starověkém Egyptě. Zjistil jsi, že už kdysi se dámy vyžívaly ve vlasových příčescích a dokonce se s nimi nechávaly i pohřbít.", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Odejít z muzea", NextLocationId = 10 } } });
            Locations.Add(409, new Location() { Name = "Muzeum", Description = "Přišel jsi ke Kostíkovi. Začali jste si povídat o dinosaurech. O těch ví Kostík nejvíc.", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Odejít z muzea.", NextLocationId = 10 } } });
            Locations.Add(410, new Location() { Name = "Muzeum", Description = "Kostík dnes neměl chuť si povídat. V tu chvíli, co jsi k němu vykročil, se Kostík otočil a vydal opačným směrem hlouběji do muzea.", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Odejít z muzea", NextLocationId = 10 } } });
            Locations.Add(411, new Location() { Name = "Muzeum", Description = "Šel ses na Dinu zeptat a paní u pokladny ti oznámila, že tu dnes Dina není.", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Odejít z muzea", NextLocationId = 10 } } });
            Locations.Add(412, new Location() { Name = "Muzeum", Description = "Dinu jsi sice našel, ale neměla na tebe čas ani náladu. Snad někdy jindy.", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Odejít z muzea", NextLocationId = 10 } } });
            Locations.Add(413, new Location() { Name = "Muzeum", Description = "Šel ses na Dinu zeptat a paní u pokladny ti poradila, kde ji hledat. Dina si tě pamatovala a ráda s tebou pokecala. Řekla ti, ať se zas někdy stavíš.", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Odejít z muzea", NextLocationId = 10 } } });
            Locations.Add(414, new Location() { Name = "Muzeum", Description = "Procházíš se už asi 10 minut, ale nic tě ne a ne zaujmout.", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Odejít z muzea", NextLocationId = 10 } } });
            Locations.Add(415, new Location() { Name = "Muzeum", Description = "Byl jsi tak zaujat všemi exponáty, že jsi ztratil pojem o čase. Je čas jít.", Paths = new List<Path>() { new Path { PathId = 0, PathDescription = "Odejít z muzea", NextLocationId = 10 } } });



            //Supermarket (500-599)
            Locations.Add(500, new Location() { Name = "Supermarket Oliplus", Description = "Ocitáš se v obchodě, je tu velký výběr všeho možného, od pečiva až po elektroniku. Co si koupíš?", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Koupit běžné potraviny", NextLocationId = 501 }, new Path() { PathId = 1, PathDescription = "Nakoupit na piknik", IsLocked = true, HoverDescription = "Nejdříve musíš splnit úkol v parku", NextLocationId = 502 }, new Path() { PathId = 2, PathDescription = "Odejít", NextLocationId = 10 } } });
            Locations.Add(501, new Location() { Name = "Supermarket Oliplus", Description = "Už máš vše, co potřebuješ a přicházíš k pokladnám.", RedirectPaths = new List<RedirectPath> { new RedirectPath() { LocationId = 505, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 507, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 511, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 512, PathId = 0, NewNextLocationId = 10 } } , Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít k pokladní", NextLocationId = 505 }, new Path() { PathId = 1, PathDescription = "Jít k pokladnímu", NextLocationId = 506 } } });
            Locations.Add(502, new Location() { Name = "Supermarket Oliplus", Description = "Máš nakoupené chipsy, ingredience na jednohubky a dobré francouzské víno.", PathToUnlock = new LocationPath() { LocationId = 207, PathId = 2}, RedirectPaths = new List<RedirectPath> { new RedirectPath() { LocationId = 505, PathId = 0, NewNextLocationId = 510 }, new RedirectPath() { LocationId = 507, PathId = 0, NewNextLocationId = 510 }, new RedirectPath() { LocationId = 511, PathId = 0, NewNextLocationId = 510 }, new RedirectPath() { LocationId = 512, PathId = 0, NewNextLocationId = 510 } }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít k pokladní", NextLocationId = 505 }, new Path() { PathId = 1, PathDescription = "Jít k pokladnímu", NextLocationId = 506 } } });
            Locations.Add(505, new Location() { Name = "Supermarket Oliplus", Description = "Za pokladnou sedí sličná prodavačka, které má na jmenovce napsáno Róza Eaglová, se na tebe usměje a říká: \"679 korunek Vás poprosím. \"", RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 501, PathId = 0, NewNextLocationId = 511}, new RedirectPath() { LocationId = 502, PathId = 0, NewNextLocationId = 511 } }, Cost = 679, Person = new Person() { Name = "Róza Eaglová", LocationId = 760, ClubLocationId = 634 }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zaplatit a odejít"} } });
            Locations.Add(506, new Location() { Name = "Supermarket Oliplus", Description = "Za pokladnou je prodavač, který má na jmenovce napsáno Emilie Lichá, což k vzhledem k jeho plnovousu nebude úplně pravdivé. Jakmile řekne jeho hlubokým můžským hlasem \"420 korun\", je ti jasné, že je to muž.", RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 501, PathId = 1, NewNextLocationId = 512 }, new RedirectPath() { LocationId = 502, PathId = 1, NewNextLocationId = 512 } }, Cost = 420, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zeptat se na jeho jmenovku", NextLocationId = 507 } } });
            Locations.Add(507, new Location() { Name = "Supermarket Oliplus", Description = "Prodavač říká: \"Víte, nechci zde prozrazovat své pravé jméno každému na potkání.\"", Person = new Person() { Name = "Neznámý prodavač", LocationId = 761, ClubLocationId = 635}, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zaplatit" } } });
            Locations.Add(510, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Máš nakoupeno na piknik, nyní můžeš vyrazit do parku a udělat si ho.\"", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Jít přímo do parku", NextLocationId = 207 }, new Path() { PathId = 1, PathDescription = "Odejít na náměstí", NextLocationId = 10 } } });

            //Supermarket 2
            Locations.Add(511, new Location() { Name = "Supermarket Oliplus", Description = "Za pokladnou sedí již pro tebe známá prodavačka. S úsměvem zaplatíš a rozloučíš se.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Vydat se od pokladny"} } });
            Locations.Add(512, new Location() { Name = "Supermarket Oliplus", Description = "Za pokladnou sedí již pro tebe známý prodavač. Nenápadně mu zkontroluješ jmenovku, a když zjistíš, že má pořád tu samou, s úsměvem zaplatíš a rozloučíš se.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Vydat se od pokladny" } } });



            //TANEČNÍ KLUB (600-699)
            Locations.Add(600, new Location() { Name = "Taneční klub Milimetr", Description = "Přicházíš ke klubu a už z dálky vidíš kroutící se frontu lidí, kteří čekají, až je pustí dovnitř.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít dál", NextLocationId = 601 }, new Path() { PathId = 0, PathDescription = "Zpět na náměstí", NextLocationId = 10 } } });
            Locations.Add(601, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Nový úkol - Dostaň se dovnitř klubu.\" ", RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 5, PathId = 0, NewNextLocationId = 608 } }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationIds = RandomLocations[RandomEnum.ClubEnter] } } });

            //před klubem
            Locations.Add(602, new Location() { Name = "Před klubem", Description = "Řada pomalu postupuje a když přijde na tebe, vyhazovač se na tebe zběžně podívá a pustí tě dovnitř.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít do klubu", NextLocationId = 606 } } });
            Locations.Add(603, new Location() { Name = "Před klubem", Description = "Komplikace se objevily dřív, než jsi myslel. Už už ses těšil, že se po dlouhém čekání ve frontě konečně dostaneš dovnitř, když tě zastaví vyhazovač. \"Máme plno, další už nemůžou dovnitř.\"", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Rozhořčeně odejít", NextLocationId = 6 }, new Path() { PathId = 0, PathDescription = "Zkusit podplatit vyhazovače", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Zkusit přemluvit dohazovače", NextLocationId = 10 }, new Path() { PathId = 2, PathDescription = "Snažit se nepozorovaně proklouznout dovnitř", NextLocationId = 10 } } });

            Locations.Add(604, new Location() { Name = "Povedlo se", Description = "Vyhazovač se opatrně podíval kolem sebe, vzal ti bankovku z ruky a rychle si ji strčil do kapsy. Pak pokynul hlavou ke vchodu.", Cost = 500, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat dovnitř", NextLocationId = 606 } } });
            Locations.Add(606, new Location() { Name = "Povedlo se", Description = "Dostal ses dovnitř klubu.", Cost = 200, Club = true, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = 5 } } });
            Locations.Add(607, new Location() { Name = "Radši jdi", Description = "Tentokrát se ti nepovedlo dostat dovnitř.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 6 } } });

            Locations.Add(608, new Location() { Name = "Taneční klub Milimetr", Description = "Uvnitř se to jenom hemží lidmi různých úrovní střízlivosti.", RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 5, PathId = 0, NewNextLocationId = 10 }, new RedirectPath() { LocationId = 600, PathId = 0, NewNextLocationId = 609} }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationId = 10 }, new Path() { PathId = 1, PathDescription = "Jít k baru", NextLocationId = 10 }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho známého", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(609, new Location() { Name = "Před klubem", Description = "Stojíš ve frontě a čekáš...", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationIds = RandomLocations[RandomEnum.ClubEnter] } } });

            //Majk Klitenda
            Locations.Add(610, new Location() { Name = "U baru", Description = "Máš štěstí a najdeš volnou stoličku. Sedneš si a mávneš na barmana. Ten vám naznačí, že vás slyšel a hned bude u tebe. Když k tobě po pár minutách přijde, automaticky mu koukneš na jmenovku.", RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 608, PathId = 1, NewNextLocationId = 617} }, Person = new Person() { Name = "Majk Klitenda", LocationId = 762}, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Objednat si pití", NextLocationId = 611 } } });
            Locations.Add(611, new Location() { Name = "U baru", Description = "V dobu, kdy je před tebe postaven tvůj objednaný drink, je na baru pouze pár lidí. Barman Majk vypadá, že je rád, že si může na chvilku odpočinout.", Cost = 120, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "V tichu popíjet", NextLocationId = 612 }, new Path() { PathId = 1, PathDescription = "Povídat si s Majkem", NextLocationId = 613 } } });
            Locations.Add(612, new Location() { Name = "Taneční klub Milimetr", Description = "Po dopití se zvedneš a jdeš se porozhlédnout po tanečním parketu.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(613, new Location() { Name = "U baru", Description = "Majk ti vypráví pár svých vtipných příhod, které se mu staly od té doby, co tu pracuje.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Zkusit najít někoho známého", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(614, new Location() { Name = "Odchod", Description = "Z klubu odcházíš unavený, ale spokojený.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 } } });
            Locations.Add(615, new Location() { Name = "Odchod", Description = "Z klubu odcházíš poměrně brzy, protože tě to tam nebavilo.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 } } });
            Locations.Add(616, new Location() { Name = "Odchod", Description = "Nejlepší noc. Užil sis na maximum.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít", NextLocationId = 10 } } });
            Locations.Add(617, new Location() { Name = "U baru", Description = "Sedneš si na stoličku a čekáš, až se ti Majk bude věnovat.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Objednat si drink", NextLocationId = 611 }, new Path() { PathId = 1, PathDescription = "Povídat si s Majkem", NextLocationIds = RandomLocations[RandomEnum.MajkOptions] } } });
            Locations.Add(618, new Location() { Name = "U baru", Description = "Majk tě zas rád viděl. Dlouho jste si povídali a nasmáli se spolu", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít z klubu", NextLocationId = 10 } } });
            Locations.Add(619, new Location() { Name = "U baru", Description = "Majk měl dost práce a tak na tebe jenom mávnul.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Zkusit najít někoho známého", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });



            //random klub možnosti
            Locations.Add(620, new Location() { Name = "HVĚZDA PARKETU", Description = "Nenašel jsi nikoho, koho bys znal. Vyrazil jsi sám na parket, kde sis to pořádně užil.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít z klubu", NextLocationId = 10 } } });
            Locations.Add(621, new Location() { Name = "ZÁCHODOVÍ DEALEŘI", Description = "Po tom, co jsi odešel na záchod po neúspěšném pátrání po někom známém, zastavil tě týpek a nabídl ti něco, co sis asi přece jenom brát neměl.", Cost = 400, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít z klubu", NextLocationId = 10 } } });
            Locations.Add(622, new Location() { Name = "RANDE SE ZÁCHODOVOU MÍSOU", Description = "Po tvém neúspěšném hledání někoho známého jsi se vydal dát si něco k pití. Barman ti byl sice určitě vděčný za tvá dýška, která se s každou skleničkou navyšovala, tvůj obličej ale dost protestuje, když strávíš zbytek noci přitisklý na záchodovou mísu.", Cost = 2500, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít z klubu", NextLocationId = 10 } } });
            Locations.Add(623, new Location() { Name = "NEVÍTANÝ SPOLEČNÍK", Description = "Po marném hledání známé tváře v davu zpocených těl ses po pár drincích přidal ke skupince pohledně vypadajících mužů a žen. Nevypadali zrovna nadšení, když jsi jim celou noc vyprávěl o svém životě a odmítal ses od nich oddělit.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Odejít z klubu", NextLocationId = 10 } } });
            Locations.Add(624, new Location() { Name = "PIJÁCI U KULATÉHO STOLU", Description = "Nenašel jsi nikoho, koho bys znal. Už už jsi chtěl odejít, když tě parta chlápků ve středním věku vtáhla k jejich stolu na partičku karet. Měl jsi štěstí a vyhrál jsi. Pár ponožek, dvě propisky a... snubní prsten?", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "", NextLocationId = 10 } } });
            Locations.Add(625, new Location() { Name = "MAN NA OBZORU", Description = "Potkal jsi Maniela.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(626, new Location() { Name = "LATTÉ SE ŠLEHAČKOU", Description = "Potkal jsi Manielu.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(627, new Location() { Name = "STAR WARS KWEEN", Description = "Potkal jsi Janu Periodu.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(628, new Location() { Name = "12, TO JE POHODA", Description = "Potkal jsi Lenku.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(629, new Location() { Name = "UTRŽENÝ ZE ŘETĚZU", Description = "Potkal jsi Pepu Hřebce.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(630, new Location() { Name = "KULMA, NŮŽKY, HŘEBEN!", Description = "Potkal jsi Zohana.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(631, new Location() { Name = "ZOHANKA", Description = "Potkal jsi Břetislavu Matějkovou.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(632, new Location() { Name = "NESMUTNI", Description = "Potkal jsi Dinu Veselou.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(633, new Location() { Name = "AŽ DO MORKU KOSTÍ", Description = "Potkal jsi Kostíka.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(634, new Location() { Name = "CHLEBA S MÁSLEM SE SALÁMEM", Description = "Potkal jsi Rózu Eaglovou.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });
            Locations.Add(635, new Location() { Name = "PEČIVO, CHLEBA, ČTYŘI ROHLÍKY", Description = "Potkal jsi Neznámého prodavače", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít tancovat", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 1, PathDescription = "Jít společně na drink k baru", NextLocationIds = RandomLocations[RandomEnum.ClubExperience] }, new Path() { PathId = 2, PathDescription = "Zkusit najít někoho jiného", NextLocationIds = RandomLocations[RandomEnum.ClubOptions] } } });




            //Rande rybník(699-709)
            Locations.Add(699, new Location() { Name = "Rybník", Description = "Dorazil jsi k rybníku. Po chvíli rozhlížení musíš uznat, že měl Havel pravdu. Tohle místo je fakt přímo stvořené na balení.", RedirectPaths = new List<RedirectPath>() { new RedirectPath() { LocationId = 701, PathId = 1, NewNextLocationId = 703 }, new RedirectPath() { LocationId = 701, PathId = 0, NewNextLocationId = 10 } }, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pozvat někoho na rande", NextLocationId = 703 }, new Path() { PathId = 0, PathDescription = "Vrátit se zpět", NextLocationId = 200 } } });
            Locations.Add(700, new Location() { Name = "SUPER!", Description = "Tvé pozvání bylo přijato.", RedirectPaths = new List<RedirectPath>() { new RedirectPath { LocationId = 200, PathId = 1, NewNextLocationId = 707 } }, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Jít na rande", NextLocationIds = RandomLocations[RandomEnum.DateSuccess] } } });
            Locations.Add(701, new Location() { Name = "SMŮLA", Description = "Tvé pozvání bylo odmítnuto.", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Zkusit to jindy", NextLocationId = 10 }, new Path { PathId = 1, PathDescription = "Zkusit pozvat někoho jiného", NextLocationId = 703 } }, DateRejected = true });
            //Locations.Add(702, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Nový úkol - Jdi s někým na rande! Tohle místo má perfektní atmosféru.\"", DateAllowed = true, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Číst dále", NextLocationId = 703 } } });
            Locations.Add(703, new Location() { Name = "Nové upozornění", Description = "Telefon: \"Na horní liště vlevo máš pod seznamem Známí uložené všechny, které jsi zatím stihl ve hře potkat. Kliknutím na jméno je můžeš pozvat na rande. Bude ale pouze na nich, jestli nabídku přijmou. Pokud netoužíš pozvat na rande nikoho ze seznamu, vyraž zpět do města poznat další lidi a pak se sem vrať.\"", DateAllowed = true, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Jít se dále seznamovat", NextLocationId = 10 } } });
            Locations.Add(704, new Location() { Name = "YESS", Description = "Tak tohle se povedlo. Celou dobu jste si měli o čem povídat a tobě se úspěšně podařilo svou milou společnost okouzlit. Jen tak dál.", DateCountUp = true, SuccessfulDateCountUp = true, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = 10 } } });
            Locations.Add(705, new Location() { Name = "NO", Description = "Tvé rande bylo fajn. Žádné extra trapasy se nekonaly, ale že by si z tebe tvoje společnost sedla na zadek, to se taky říct nedá. Příště se polepši.", DateCountUp = true, SuccessfulDateCountUp = true, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = 10 } } });
            Locations.Add(706, new Location() { Name = "JEJDA", Description = "Tak jestli si myslíš, že tě po tomhle výkonu bude tvá společnost ještě někdy chtít vidět, tak jsi na hlavu. Ceníme ale tvé sebevědomí. Nevěš hlavu a zkus to příště s někým jiným.", DateCountUp = true, DateRejected=true, Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = 10 } } });
            Locations.Add(707, new Location() { Name = "Rybník", Description = "Jsi u rybníku. Odtud můžeš znovu někoho ze svého seznamu pozvat na rande.", DateAllowed = true, Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Zpět na náměstí a jít se dále seznamovat", NextLocationId = 10 } } });

            //Osoby - na rande
            Locations.Add(750, new Location() { Name = "Maniel", DateWithPerson = true, Description = "Maniel, nebo také Man, jak mu jeho kamarádi říkají, je mladý pohledný jinoch, který tě jistě překvapí svým neobvyklým vzhledem.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(751, new Location() { Name = "Maniela", DateWithPerson = true, Description = "Maniela je rychlá, pečlivá a svědomitá dívka.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(752, new Location() { Name = "Zohan", DateWithPerson = true, Description = "Zohan je vyučený kadeřník a provozuje své vlastní kadeřnictví. Je to uznávaný profesionál ve svém oboru.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(753, new Location() { Name = "Břetislava Matějková", DateWithPerson = true, Description = "Břetislava je v kadeřnictví nová. Je bojácná, ale hodná.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(754, new Location() { Name = "Havel Škrlík", DateWithPerson = true, Description = "Ač jsou Havlova nejlepší léta již dávno pryč, stále má jiskru v oku. 😉", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(755, new Location() { Name = "Pepa Hřebec", DateWithPerson = true, Description = "Pepa je velmi svérázný muž. Někoho tím upoutá, jiného odežene.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(756, new Location() { Name = "Jana Perioda", DateWithPerson = true, Description = "Jana je opravdu příjemná a moc milá dívka.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(757, new Location() { Name = "Lenka", DateWithPerson = true, Description = "Nejdříve se Lenka zdá jako nanápadná osůbka, ale opak je pravdou. Je to pořádná dračice.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(758, new Location() { Name = "Dina Veselá", DateWithPerson = true, Description = "Dina se zodpovědně věnuje své práci v muzeu, proto se od ní dozvíš mnoho historických zajímavostí i v soukromí.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(759, new Location() { Name = "Kostík", DateWithPerson = true, Description = "Kostík je opravdu zvláštní osoba, ale vždy tě dokáže něčím zaujmout.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(760, new Location() { Name = "Róza Eaglová", DateWithPerson = true, Description = "Róza... to je ta půvabná prodavačka, na kterou se těšíš při každém nákupu v Oliplusu.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(761, new Location() { Name = "Neznámý prodavač", DateWithPerson = true, Description = "Setkali jste s supermarketu u kasy, ale jeho pravé jméno nevíš. Jak se asi jmenuje?", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });
            Locations.Add(762, new Location() { Name = "Majk Klitenda", DateWithPerson = true, Description = "Majk je fakt borec. A na parketu to umí rozjet.", Paths = new List<Path> { new Path() { PathId = 0, PathDescription = "Pokračovat", NextLocationId = GetRandom(RandomEnum.Date) } } });

            Locations.Add(800, new Location() { Name = "Upozornění", Description = "Potkal jsi a byl jsi odmítnut všemi lidmi před dosažením cíle. Buď můžeš hru hned ukončit, nebo si můžeš dále procházet městečko. Pro ukončení hry stačí kdykoliv zmáčknout tlačítko \"Konec hry\", které je umístěno na horní liště vlevo. ", Paths = new List<Path>() { new Path() { PathId = 0, PathDescription = "Pokračovat ve hře", NextLocationId = 10} } });
        }


    }
}